### ISSUE TITLE
Music from chrome (youtube) not appearing in overlay

### ISSUE THREAD

**Issue by WhyIsEveryUsernameIsAlreadyTaken** [Nerixyz/current-song2#107]
With the extension installed, playing something from youtube won't show up on the overlay, but playing something from spotify will show up on the overlay.

https://user-images.githubusercontent.com/51572004/185769903-9c3c0fcf-ec1e-496d-81d3-5dcb42ea8cd2.mp4

![image](https://user-images.githubusercontent.com/51572004/185769937-169606af-1af3-46db-ba7f-d9a52f338509.png)

A week or two ago it had been working, but I'm unsure if in the time since then something changed with the extension or with my setup.

And I apologize in advance if I'm just missing something very obvious and or if this is a duplicate issue.

Thanks!

**Comment by Nerixyz** [comment]
I tested it on my end and including chrome worked fine on both YouTube and YouTube Music.

> changed with the extension

For "basic" song info (i.e. title, artist and image) you don't _need_ the extension. Chrome will broadcast one tab to the system's media control (so the overlay should appear even without the extension in this case). 

Also, which extension are you using (the one from the chrome-web-store is for `current-song(-1)` but I plan to update the extension to the one developed here).

**Comment by WhyIsEveryUsernameIsAlreadyTaken** [comment]
I'm using the one linked in the readme, in the setup section. Is there a different one I should be using?

**Comment by WhyIsEveryUsernameIsAlreadyTaken** [comment]
Still getting the same results it seems...

**Comment by WhyIsEveryUsernameIsAlreadyTaken** [comment]
I decided to check the console in http://localhost:48457/ and saw this error:
`Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.`
which was being caused by another extension I had. Removing it got rid of that error, and the server started picking up info from chrome again.
