### ISSUE TITLE
More Metadata from Files and Current CSS Variable

### ISSUE THREAD

**Issue by SEGACD32XMODEL1** [Nerixyz/current-song2#162]
Can we add ways to display more metadata than Title and Artist? Like album and track number? Can we also get the variable for the current time in CSS globally for style purposes?

**Comment by Nerixyz** [comment]
This should be possible.

Sub-Tasks (for me or anyone implementing this):

* [ ] GSMTC can provide `AlbumTitle`, `TrackNumber`, and `AlbumTrackCount` ([src](https://microsoft.github.io/windows-docs-rs/doc/windows/Media/Control/struct.GlobalSystemMediaTransportControlsSessionMediaProperties.html)).
* [ ] The extension can provide the `artist` and `album`(-title) ([src](https://developer.mozilla.org/en-US/docs/Web/API/MediaMetadata)).
* [ ] `--progress` can be lifted to the `body` element.
* [ ] Consider adding data attributes/classes like `[no-]album`, `[no-]track`, `single-track`
