### ISSUE TITLE
Publish win-gsmtc to crates.io?

### ISSUE THREAD

**Issue by gyng** [Nerixyz/current-song2#291]
I'm toying with GlobalSystemMediaTransportControlsSessionManager and I see you've already put in a bunch of work into getting it usable.

Are there plans to publish it to crates.io as a standalone crate? It seems fairly complete from a quick scan.

**Comment by Nerixyz** [comment]
Yea, I can do that. I'll add some documentation. Keep in mind that it currently depends on `tokio`. Example usage:

```rust
let mut rx = SessionManager::new().await?;
while let Some(evt) = rx.recv().await {
  match evt {
    ManagerEvent::SessionCreated { mut rx, source, .. } => {
      // Sessions have their own stream.
      tokio::spawn(async move {
        while let Some(evt) = rx.recv().await {
          match evt {
              SessionUpdateEvent::Model(model) => {
                  dbg!((&source, &model));
              }
              SessionUpdateEvent::Media(model, image) => {
                  dbg!((&source, &model, &image));
              }
          }
        }
      });
    }
  }
}
```

There are some design decisions that were made specifically for this project - e.g. `SessionUpdateEvent` _could_ send the `model` in an `Arc` rather than copying it every time.

**Comment by gyng** [comment]
Hey, thanks for this! I've cobbled together a toy now playing widget in Tauri using your library: https://github.com/gyng/np-widget/blob/bfd3163d2c769bce2d4a19ec7098c0a970b82f16/np/src/main.rs.
