### ISSUE TITLE
on obs browser, marquee not working when title has overflow 

### ISSUE THREAD

**Issue by kurosoft** [Nerixyz/current-song2#357]
on windows 10, using brave browser it's working properly.
on obs browser, text is not scrolling / marquee is not working 

brave browser
![image](https://github.com/Nerixyz/current-song2/assets/6907097/4d359b09-adfa-44dc-b583-e34feb5d0071)

obs browser
![image](https://github.com/Nerixyz/current-song2/assets/6907097/fa3fb6e3-616c-48d2-b48b-e1089a3faf49)

with devtools
![image](https://github.com/Nerixyz/current-song2/assets/6907097/c6a84f53-329a-4dcc-a749-5b4bd7334c87)

**Comment by Nerixyz** [comment]
This seems to be a Chromium bug affecting Chrome <113 - OBS currently ships Chromium 103. The `clientWidth` of the element that detects the overflow is alternating between two values.
