### ISSUE TITLE
make the webserver reachable by another PC on the local network

### ISSUE THREAD

**Issue by deudtens163** [Nerixyz/current-song2#454]
Hello,

is there any way to make the webserver reachable by another PC in the local network ?

I explain : I use a setup in wich the VideoPC where i want tu use the overlay is not the PC playing the music.
I wish i could connect to the current-song2 websocket directly from the VideoPC.
I tried to replace the rollback adress by the IP adress of the MusicPlayingPC in the url but this doesn't work.
Is there already a way to do it ?

**Comment by deudtens163** [comment]
Response to myself : must be a firewall issue, try to open traffic on the port of webserver

**Comment by Nerixyz** [comment]
>  must be a firewall issue, try to open traffic on the port of webserver

It's not a firewall issue, the server only listens on localhost:

https://github.com/Nerixyz/current-song2/blob/e1162f4e3c6e06fe6ed5e5d6e0aa0dc96dbd1fa6/src/main.rs#L106

I'll add a config option to set the bind-address.

**Comment by Nerixyz** [comment]
Released in https://github.com/Nerixyz/current-song2/releases/tag/v0.1.0-alpha.11.

**Comment by deudtens163** [comment]
thank you for your very fast response

**Comment by deudtens163** [comment]
Hello, for me there is another issue to remote connect to the http server from another PC in the network :
the line under forces the ws to connect to localhost.
https://github.com/Nerixyz/current-song2/blob/8ad19bc46ba78445b2e85acc44553fca0ca8ba0d/js/shared/url.ts#L5
Am I true ?

**Comment by Nerixyz** [comment]
Right, fixed in https://github.com/Nerixyz/current-song2/releases/tag/v0.1.0-alpha.12.

**Comment by deudtens163** [comment]
Infos working properly 👍
Progression Bar fonctionnal but not accurate, doesn't synchonise well on distant PC but good locally
Must still be an error with processing of image url
![Capture d'écran 2024-06-22 142855](https://github.com/Nerixyz/current-song2/assets/48241838/bf9562f1-2226-4712-be53-781dde1e4d4e)

**Comment by Nerixyz** [comment]
I'm so sorry for missing that 😅 It should be fixed in https://github.com/Nerixyz/current-song2/releases/tag/v0.1.0-alpha.13 (with a few dependency updates and refactorings).

**Comment by deudtens163** [comment]
Thank you so much, you've been really very reactive to add this functionality. Great Work !
