### ISSUE TITLE
Resize issue

### ISSUE THREAD

**Issue by AzzyDreamer** [Nerixyz/current-song2#507]
Hi. 
I was wondering if there is any way of increasing the resolution via config.toml or theme.css?

Thanks in advance.

**Comment by Nerixyz** [comment]
You can experiment with the CSS `transform: scale(123%)` property in `theme.css`. Note that some animations [change the scaling too](https://github.com/Nerixyz/current-song2/blob/72120f96b8b8cb6cfa5ed6525aa8d2f36057688d/js/client/src/index.css#L114-L121).

**Comment by Nerixyz** [comment]
That probably has to do with the `transform-origin` property, which is currently set to `left`. In this case, it should be `top left`.
