### ISSUE TITLE
Config Overwritten Every Restart

### ISSUE THREAD

**Issue by SPL17SCR33N** [Nerixyz/current-song2#56]
When trying to close the app and relaunch it to see if css changes have been applied, the app remakes its config file and overwrites any changes, making it impossible to ever change the theme.

**Comment by Nerixyz** [comment]
It only overwrites the config if the old config can't be read:

https://github.com/Nerixyz/current-song2/blob/da95a4582c450b1c1daf6037dded495c5742adf2/src/config.rs#L105-L116

What's your config? I'll try to test it.

**Comment by Nerixyz** [comment]
Backslashes (`\`) are used as escapes in toml, so you either have to esacpe them (i.e. replace `\` with `\\`) or use forward slashes.

This is how the path should look like:

```toml
custom_theme_path = "C:\\Users\\rcgam3r\\Downloads\\OBS Current Song\\blurred-bg-slide.css"
```
or
```toml
custom_theme_path = "C:/Users/rcgam3r/Downloads/OBS Current Song/blurred-bg-slide.css"
```

**Comment by SPL17SCR33N** [comment]
That was the problem, thank you for the help!
